-- Supabase setup entrypoint
-- =========================
--
-- The complete SQL for the current database lives here:
--
--   supabase/migrations/202608210001_wedding_persistence.sql
--   supabase/migrations/202608210002_dashboard_passcode_rpc.sql
--   supabase/migrations/202608210003_allow_multiple_gift_card_pledges.sql
--   supabase/migrations/202608210004_require_phone_contacts.sql
--
-- Run both migrations in Supabase Dashboard > SQL Editor for a new database.
-- They create:
--   - public.rsvps
--   - public.gift_reservations
--   - public.guest_photos
--   - public.public_gift_reservations
--   - public.dashboard_wedding_stats
--   - public.couple_admins
--   - public.dashboard_passcodes
--   - wedding-guest-photos storage bucket
--   - RLS policies for guests, dashboard access, and couple admins
--   - multiple gift-card pledges while keeping physical gifts unique
--   - required RSVP/gift pledge phone contacts for new records
--
-- Set or change the no-login dashboard password with:
--
-- insert into public.dashboard_passcodes (id, passcode_hash)
-- values ('couple', extensions.crypt('CHANGE_THIS_TO_THE_REAL_DASHBOARD_PASSWORD', extensions.gen_salt('bf')))
-- on conflict (id) do update
-- set passcode_hash = excluded.passcode_hash,
--     updated_at = now();
