-- Run once in Supabase Dashboard > SQL Editor.
-- This sets up shared gift tracking and the public guest-photo gallery.

create table if not exists public.gift_reservations (
  id bigint generated by default as identity primary key,
  gift_id text not null unique,
  gift_title text not null,
  giver_name text not null check (char_length(giver_name) between 1 and 160),
  contact_no text,
  created_at timestamptz not null default now()
);

alter table public.gift_reservations enable row level security;

drop policy if exists "Guests can reserve available gifts" on public.gift_reservations;
create policy "Guests can reserve available gifts"
on public.gift_reservations for insert to anon
with check (true);

-- This view intentionally hides private contact numbers from public visitors.
create or replace view public.public_gift_reservations
with (security_invoker = true) as
select gift_id, gift_title, giver_name, created_at
from public.gift_reservations;

revoke all on table public.gift_reservations from anon;
grant insert on table public.gift_reservations to anon;
grant usage, select on sequence public.gift_reservations_id_seq to anon;
grant select on public.public_gift_reservations to anon;

-- The view needs a safe SELECT policy on its source table, while column grants
-- prevent the browser role from selecting contact_no directly.
drop policy if exists "Guests can see public gift status" on public.gift_reservations;
create policy "Guests can see public gift status"
on public.gift_reservations for select to anon
using (true);
grant select (gift_id, gift_title, giver_name, created_at) on public.gift_reservations to anon;

create table if not exists public.guest_photos (
  id bigint generated by default as identity primary key,
  storage_path text not null unique,
  public_url text not null,
  uploader_name text not null check (char_length(uploader_name) between 1 and 160),
  caption text not null default '',
  event_type text not null default 'general' check (event_type in ('traditional', 'white', 'general')),
  created_at timestamptz not null default now()
);

alter table public.guest_photos
add column if not exists event_type text not null default 'general';

alter table public.guest_photos enable row level security;

drop policy if exists "Anyone can view guest photos" on public.guest_photos;
create policy "Anyone can view guest photos"
on public.guest_photos for select to anon
using (true);

drop policy if exists "Guests can add photo metadata" on public.guest_photos;
create policy "Guests can add photo metadata"
on public.guest_photos for insert to anon
with check (true);

grant select, insert on table public.guest_photos to anon;
grant usage, select on sequence public.guest_photos_id_seq to anon;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'wedding-guest-photos',
  'wedding-guest-photos',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Guests can upload wedding photos" on storage.objects;
create policy "Guests can upload wedding photos"
on storage.objects for insert to anon
with check (bucket_id = 'wedding-guest-photos');

drop policy if exists "Anyone can view wedding photos" on storage.objects;
create policy "Anyone can view wedding photos"
on storage.objects for select to anon
using (bucket_id = 'wedding-guest-photos');
