-- Couple dashboard passcode access.
--
-- This supports the requested flow:
--   1. Guest enters normal invitation code => invitation opens.
--   2. Couple enters dashboard password in the same field => dashboard opens.
--
-- The password is NOT stored in the frontend. Store only a bcrypt-style hash
-- generated by pgcrypto's crypt()/gen_salt().

begin;

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create table if not exists public.dashboard_passcodes (
  id text primary key default 'couple',
  passcode_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.dashboard_passcodes enable row level security;

drop trigger if exists set_dashboard_passcodes_updated_at on public.dashboard_passcodes;
create trigger set_dashboard_passcodes_updated_at
before update on public.dashboard_passcodes
for each row execute function public.set_updated_at();

-- No direct browser access to hashes.
revoke all on table public.dashboard_passcodes from anon, authenticated;

create or replace function public.is_valid_dashboard_passcode(passcode text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.dashboard_passcodes
    where id = 'couple'
      and passcode is not null
      and length(trim(passcode)) > 0
      and extensions.crypt(passcode, passcode_hash) = passcode_hash
  );
$$;

revoke all on function public.is_valid_dashboard_passcode(text) from public;
grant execute on function public.is_valid_dashboard_passcode(text) to anon, authenticated;

create or replace function public.get_couple_dashboard(passcode text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.is_valid_dashboard_passcode(passcode) then
    raise exception 'Invalid dashboard password' using errcode = '28000';
  end if;

  return jsonb_build_object(
    'stats', jsonb_build_object(
      'total_rsvps', (select count(*) from public.rsvps),
      'attending_rsvps', (select count(*) from public.rsvps where attendance <> 'decline'),
      'expected_guests', (select coalesce(sum(guest_count), 0) from public.rsvps where attendance <> 'decline'),
      'declined_rsvps', (select count(*) from public.rsvps where attendance = 'decline'),
      'reserved_gifts', (select count(*) from public.gift_reservations where status in ('reserved', 'contacted', 'fulfilled')),
      'uploaded_photos', (select count(*) from public.guest_photos where status = 'published')
    ),
    'rsvps', coalesce((
      select jsonb_agg(to_jsonb(row_data) order by row_data.created_at desc)
      from (
        select
          id,
          full_name,
          phone,
          email,
          attendance,
          guest_count,
          message,
          whatsapp_link_opened,
          status,
          notes,
          created_at
        from public.rsvps
        order by created_at desc
        limit 200
      ) row_data
    ), '[]'::jsonb),
    'gift_reservations', coalesce((
      select jsonb_agg(to_jsonb(row_data) order by row_data.created_at desc)
      from (
        select
          id,
          gift_id,
          gift_title,
          giver_name,
          contact_no,
          status,
          notes,
          created_at
        from public.gift_reservations
        order by created_at desc
        limit 200
      ) row_data
    ), '[]'::jsonb),
    'guest_photos', coalesce((
      select jsonb_agg(to_jsonb(row_data) order by row_data.created_at desc)
      from (
        select
          id,
          storage_path,
          public_url,
          uploader_name,
          caption,
          event_type,
          status,
          created_at
        from public.guest_photos
        order by created_at desc
        limit 200
      ) row_data
    ), '[]'::jsonb)
  );
end;
$$;

revoke all on function public.get_couple_dashboard(text) from public;
grant execute on function public.get_couple_dashboard(text) to anon, authenticated;

create or replace function public.update_dashboard_rsvp_status(
  passcode text,
  rsvp_id uuid,
  next_status text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_row public.rsvps;
begin
  if not public.is_valid_dashboard_passcode(passcode) then
    raise exception 'Invalid dashboard password' using errcode = '28000';
  end if;

  if next_status not in ('new', 'seen', 'confirmed', 'needs_follow_up', 'archived') then
    raise exception 'Invalid RSVP status';
  end if;

  update public.rsvps
  set status = next_status
  where id = rsvp_id
  returning * into updated_row;

  if not found then
    raise exception 'RSVP not found';
  end if;

  return to_jsonb(updated_row);
end;
$$;

revoke all on function public.update_dashboard_rsvp_status(text, uuid, text) from public;
grant execute on function public.update_dashboard_rsvp_status(text, uuid, text) to anon, authenticated;

create or replace function public.update_dashboard_gift_status(
  passcode text,
  reservation_id uuid,
  next_status text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_row public.gift_reservations;
begin
  if not public.is_valid_dashboard_passcode(passcode) then
    raise exception 'Invalid dashboard password' using errcode = '28000';
  end if;

  if next_status not in ('reserved', 'contacted', 'fulfilled', 'cancelled') then
    raise exception 'Invalid gift reservation status';
  end if;

  update public.gift_reservations
  set status = next_status
  where id = reservation_id
  returning * into updated_row;

  if not found then
    raise exception 'Gift reservation not found';
  end if;

  return to_jsonb(updated_row);
end;
$$;

revoke all on function public.update_dashboard_gift_status(text, uuid, text) from public;
grant execute on function public.update_dashboard_gift_status(text, uuid, text) to anon, authenticated;

create or replace function public.update_dashboard_photo_status(
  passcode text,
  photo_id uuid,
  next_status text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_row public.guest_photos;
begin
  if not public.is_valid_dashboard_passcode(passcode) then
    raise exception 'Invalid dashboard password' using errcode = '28000';
  end if;

  if next_status not in ('published', 'hidden', 'flagged') then
    raise exception 'Invalid photo status';
  end if;

  update public.guest_photos
  set status = next_status
  where id = photo_id
  returning * into updated_row;

  if not found then
    raise exception 'Photo not found';
  end if;

  return to_jsonb(updated_row);
end;
$$;

revoke all on function public.update_dashboard_photo_status(text, uuid, text) from public;
grant execute on function public.update_dashboard_photo_status(text, uuid, text) to anon, authenticated;

commit;

-- After running this migration, set or change the dashboard password with:
--
-- insert into public.dashboard_passcodes (id, passcode_hash)
-- values ('couple', extensions.crypt('CHANGE_THIS_TO_THE_REAL_DASHBOARD_PASSWORD', extensions.gen_salt('bf')))
-- on conflict (id) do update
-- set passcode_hash = excluded.passcode_hash,
--     updated_at = now();
